language: ruby
rvm:
- 2.2.3
cache: bundler
script: bundle exec rake
addons:
  code_climate:
    repo_token:
      secure: EEQ24se1YhmTSlpHI47yrlAQi1s36WOj9Sk9WDecpKjZFYJ8gSyS0nVhUAPi4rG84KyJARUd0uGNHBOhJ/ZH2YN3Ge4kxzJZEbSKQ9F65MW0VZelcL5DtIsdEoiuZ6BZ1fGM9RYnPnk4jwHn8JeZ/XyVPmSvhmShmwwcWNjY5hqGw2KWHqOvgiw9fWNn/9r1iq+pUQAjqrsjjeih5fC5nrh570mt1sY51ogFbnfI6vO5JpqLcK6v1PO4gejYharfE4zqMiBwWf4HWduyQNUVC/4pKa8ohwh8yQoInieLcweLosOTRPulBuE9Hu3EXSv4JRbNhBtREjRva8YfG7epSlQddlyc5LITwZgpw2nLDLxkGjXH0JZ9g02y5uorCiwcU3amVtrxusqpYmq6zl7o6LxNnPhCbWrMdRveXmTPpS/rL5G8DAKS7/VRylXvy4nrPbbpvwrNicyRJeFrgXREA0KXaYAOTGL4C4yrhY0LPxjbwGzL6goD2U6dxja0SDovyWPbiXIlDxPX4tn09LxdzPMdHBqfFb/oqJiLrn0vp7kn736VrvhMfU3BweLEjlCXbSmLy+h5l8d118EpZOs/BnOdqjqtAb5eztiyBHZaaJG1H6cAxCST40yCx7nhAeEti5Zt/EVyBbUyZFcJiNbvQv5jbbaX7LA4nI4Y4pmduQA=
