language: ruby
rvm:
- 2.2.3
cache: bundler
script: bundle exec rake
addons:
  code_climate:
    repo_token:
      secure: khKnZtirxlF00mULEjf2X/vLceN5zHBEglWDG2I9CIYSGDN6vudDL7llV19ndB6nrzCdMx3EoV3dctoTd9WvQltIoMiQB/WTOsGxERgHXfbzTdCNoRILqSL2tKuvfrbRChLE1fHt0AJXnHd0KwkoBBZcoAD826mrmvmDwy4F3RaYT1Qb/SC+Sd3l6jCKn46vkZ6Qj9narggRcJs2dKqPfwSgBYVvrl3lZYc6uVx9TSpNE2eprGfsnC9fix29ZAeB0pww5R5ViVooMLu+EWtKLUZpjXbXtglf+hTPrm5HdYy+ZRmIdrPNc1vUjAQsy6SzWyTG6tuDXG64Zf6lfngIBguc3wgldnUU3l04Ybt88FoWFE329liLs5PIZvpxZs/GrT+NxrHZUbLVXCoBdYKBo/Nv1WMxT+Pp8a6F9gj+e6DAjdFoCUfuuld7rxfmsvtHJLO7XnyimrE3UEt3MhizAhbbPJBbr/AlLVht6IzK1xbfuOFqm2btdy0kD8iB+mQDgdkTY+/5TrfmIagGgqfwIycJ7pp9ihl5+s2TOiZEaiDoQ/bAL2/2GpRitDal/SPvtBZGiRRAl9iWgV1KDud2dwlRig5pSS0rHH5ZQWXt7XC/Lg/TMkqIN+KIH19Lkpxh/1lntISkruEmNf3mIi+pZLFQWBbp5Q9FM0P6BoWbRsI=
